'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Courses', [
      {
        id: 'course_uuid1',
        title: 'Frontend Developer',
        description: 'Learn the fundamentals of web development, including HTML5, CSS3, and JavaScript, to build modern and responsive web pages.',
        category: 'Web Development',
        level: 'Beginner',
        duration: '6 weeks',
        price: 99.99,
        image_url: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'John Doe',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid2',
        title: 'Advance Front-End Developer',
        description: 'Master front-end technologies with React, Vue.js, and modern CSS frameworks to create dynamic and interactive web applications.',
        category: 'Web Development',
        level: 'Advanced',
        duration: '8 weeks',
        price: 149.99,
        image_url: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&q=80&w=640',
        is_published: true,
        instructor: 'Jane Smith',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid3',
        title: 'Back-End Developer',
        description: 'Focus on server-side programming with Node.js, Express, Django, and Flask to build robust back-end applications.',
        category: 'Web Development',
        level: 'Intermediate',
        duration: '10 weeks',
        price: 139.99,
        image_url: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'Emily Davis',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid4',
        title: 'Advance Back-End Developer',
        description: 'Focus on server-side programming with Node.js, Express, Django, and Flask to build robust back-end applications.',
        category: 'Web Development',
        level: 'Advanced',
        duration: '10 weeks',
        price: 179.99,
        image_url: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'Emily Davis',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid5',
        title: 'Full-Stack Developer',
        description: 'Learn end-to-end application development with MERN and MEAN stacks, integrating front-end and back-end technologies.',
        category: 'Web Development',
        level: 'Intermediate',
        duration: '12 weeks',
        price: 199.99,
        image_url: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=640',
        is_published: true,
        instructor: 'Michael Brown',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid6',
        title: 'Advanced Full-Stack Developer',
        description: 'Explore cutting-edge tools like the T3 Stack and Astro to optimize performance and build modern web applications.',
        category: 'Web Development',
        level: 'Advanced',
        duration: '10 weeks',
        price: 219.99,
        image_url: 'https://images.unsplash.com/photo-1457305237443-44c3d5a30b89?q=80&w=1748&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'Olivia Martinez',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid7',
        title: 'Cloud-Optimized Developer',
        description: 'Learn to build scalable and serverless applications using Next.js, Firebase, and AWS Lambda for cloud deployment.',
        category: 'Cloud Computing',
        level: 'Intermediate',
        duration: '10 weeks',
        price: 179.99,
        image_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'David Johnson',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid8',
        title: 'Mobile-Friendly Developer',
        description: 'Develop mobile-first and hybrid web applications with React Native and Ionic frameworks, ensuring cross-platform compatibility.',
        category: 'Mobile Development',
        level: 'Intermediate',
        duration: '8 weeks',
        price: 159.99,
        image_url: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'Sophia Wilson',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'course_uuid9',
        title: 'Enterprise Developer',
        description: 'Create enterprise-grade applications with Spring Boot, React, and ASP.NET Core, focusing on scalability and performance.',
        category: 'Web Development',
        level: 'Advanced',
        duration: '14 weeks',
        price: 249.99,
        image_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        is_published: true,
        instructor: 'James Anderson',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Courses', null, {});
  },
};
