'use strict';

const { v4: uuidv4 } = require('uuid');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('lessons', [
      {
        id: uuidv4(),
        title: 'Introduction to HTML',
        content: 'This lesson covers the fundamentals of HTML, including the basic structure of an HTML document and essential tags such as <html>, <head>, <body>, and more.',
        order_index: 1,
        module_id: '3a5c9d73-0f18-42c1-9fc2-b6d2961390a2',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Understanding CSS Selectors',
        content: 'This lesson explores various CSS selectors (element, class, ID) and demonstrates how to apply styles to HTML elements.',
        order_index: 1,
        module_id: '0a6af787-850b-42f9-982c-4020ed634f60',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Variables and Data Types',
        content: 'In this lesson, we will explore JavaScript variables, data types (strings, numbers, arrays, etc.), and how to use them effectively in a program.',
        order_index: 1,
        module_id: '56efeab4-c83c-45ff-8946-b6629f9229d0',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Getting Started with React',
        content: 'This lesson introduces you to React, including setting up a simple React app and understanding the basic concepts such as components and props.',
        order_index: 1,
        module_id: '9fbff9fc-6ddb-495f-bacc-79470a2f7657',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Using React Hooks',
        content: 'This lesson will teach you about React Hooks, including useState and useEffect, and demonstrate how they simplify state management in functional components.',
        order_index: 1,
        module_id: '3d2e4367-f310-44eb-aa3a-65d060a04c4d',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Introduction to Vue.js',
        content: 'Learn the basics of Vue.js in this lesson, including its structure, directives, and components.',
        order_index: 1,
        module_id: '915aff58-f6e1-44bd-ba07-0e425c40bbb0',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Setting up Node.js',
        content: 'This lesson will guide you through setting up a Node.js environment and writing a basic Node.js application.',
        order_index: 1,
        module_id: '15864b04-78b1-42d4-890b-c9b59b1b4175',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Creating RESTful APIs with Express.js',
        content: 'Learn how to create RESTful APIs using the Express.js framework, including setting up routes and handling HTTP requests.',
        order_index: 1,
        module_id: 'dfe5bc2f-57a9-43ec-8833-22c4fd21e176',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Introduction to MongoDB',
        content: 'In this lesson, you will learn how to connect to MongoDB, perform CRUD operations, and manage databases for your back-end applications.',
        order_index: 1,
        module_id: '2786c96e-ba7e-47fe-9fce-a608dc58c294',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Building Full-Stack Applications',
        content: 'In this lesson, we will integrate Node.js, Express, and MongoDB to build a full-stack web application.',
        order_index: 1,
        module_id: 'd4398b70-2528-41e6-ae9c-c5a85164b07a',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Working with Streams in Node.js',
        content: 'Learn how to use Node.js streams for handling large amounts of data efficiently in this lesson.',
        order_index: 1,
        module_id: 'e1f08b64-cd0e-4083-9591-ad3243f36307',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Securing Web Applications',
        content: 'This lesson focuses on securing web applications, including using HTTPS, authentication, and protecting against common security vulnerabilities.',
        order_index: 1,
        module_id: 'e6c6031d-6c24-473c-9787-23974b8ac30c',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Setting Up MERN Stack',
        content: 'Learn how to set up the MERN (MongoDB, Express, React, Node.js) stack in this lesson, and build the foundation of a full-stack application.',
        order_index: 1,
        module_id: 'a5a7616f-c087-4921-a66a-c5455ca986ca',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Integrating React with Node.js and Express',
        content: 'In this lesson, you will learn how to connect your React front-end with a Node.js back-end to build a full-stack application.',
        order_index: 1,
        module_id: '86b4700d-488f-4085-b322-81ca4ea9e3ee',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        id: uuidv4(),
        title: 'Deploying MERN Apps to Cloud Platforms',
        content: 'Learn how to deploy your MERN stack applications to cloud platforms such as AWS and Heroku in this lesson.',
        order_index: 1,
        module_id: 'bd4be254-fb68-466f-a6e9-c6f0deb03fd8',
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('lessons', null, {});
  },
};
